# Generated by Django 3.2.7 on 2021-09-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofiles',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
