# Generated by Django 3.2.7 on 2021-09-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customerprofiles_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofiles',
            old_name='customer_name',
            new_name='user',
        ),
    ]
