# Generated by Django 3.2.7 on 2021-09-22 06:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_customer_name_customerprofiles_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_legend', models.URLField(max_length=300)),
                ('second_level_one', models.URLField(max_length=300)),
                ('second_level_two', models.URLField(max_length=300)),
                ('second_level_three', models.URLField(max_length=300)),
                ('second_level_four', models.URLField(max_length=300)),
                ('second_legend_image', models.URLField(max_length=300)),
                ('second_legend_text', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='legend_image',
        ),
        migrations.AddField(
            model_name='customerprofiles',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(default='Anon Visitor', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
