# Generated by Django 3.2.7 on 2021-09-22 13:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210922_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='legend_text',
            field=ckeditor.fields.RichTextField(default='70% Off'),
        ),
    ]
