# Generated by Django 3.2.7 on 2021-09-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_promotion_legend_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfYcwp8-22XlEX4lZe_PM6PeNoFy5EMgdQMw&usqp=CAU', max_length=350),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtav_T24wgWwQXtL5_CSuCahv5jT_q0ZXKNw&usqp=CAU', max_length=350),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='header_legend',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='second_legend_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='second_level_four',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='second_level_one',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='second_level_three',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='second_level_two',
            field=models.URLField(max_length=500),
        ),
    ]
