# Generated by Django 3.2.7 on 2021-09-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210922_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='header_legend',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtav_T24wgWwQXtL5_CSuCahv5jT_q0ZXKNw&usqp=CAU', max_length=300),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='second_legend_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtav_T24wgWwQXtL5_CSuCahv5jT_q0ZXKNw&usqp=CAU', max_length=300),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='second_level_four',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtav_T24wgWwQXtL5_CSuCahv5jT_q0ZXKNw&usqp=CAU', max_length=300),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='second_level_one',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtav_T24wgWwQXtL5_CSuCahv5jT_q0ZXKNw&usqp=CAU', max_length=300),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='second_level_three',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtav_T24wgWwQXtL5_CSuCahv5jT_q0ZXKNw&usqp=CAU', max_length=300),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='second_level_two',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtav_T24wgWwQXtL5_CSuCahv5jT_q0ZXKNw&usqp=CAU', max_length=300),
        ),
    ]
